import {Platform, StyleSheet} from 'react-native';
import colors from '../../helper/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  swiper: {
    height: 300,
  },
  productImage: {
    width: '100%',
    height: 300,
    borderRadius: 15,
  },
  pagination: {
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
  },
  dash: {
    backgroundColor: colors.white,
    width: 24,
    height: 5,
    borderRadius: 2,
    marginHorizontal: 3,
  },
  activeDash: {
    backgroundColor: '#FE8C00',
    width: 24,
    height: 5,
    borderRadius: 2,
    marginHorizontal: 3,
  },
  productInfo: {
    paddingVertical: 15,
  },
  productName: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 5,
    color: colors.black,
  },
  description: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 5,
    color: colors.black,
  },
  similarTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    // paddingHorizontal: 15,
    color: colors.black,
  },
  productPrice: {
    fontSize: 20,
    color: '#FE8C00',
    marginBottom: 5,
  },
  productDeliveryInfo: {
    fontSize: 15,
    color: colors.grayDark,
  },
  productDescription: {
    marginVertical: 15,
    fontSize: 14,
    color: '#666',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 15,
  },
  iconCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  cartSection: {
    position: 'absolute', // Закрепляем секцию
    bottom: Platform.OS === 'ios' ? 30 : 0,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: '#ccc',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityText: {
    fontSize: 18,
    fontWeight: '600',
    marginHorizontal: 10,
    color: colors.black,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FE8C00',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  icon: {
    marginRight: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  line: {
    width: '100%',
    height: 2,
    marginBottom: 15,
    backgroundColor: colors.grayLight,
  },
  columnWrapper: {
    justifyContent: 'space-between',
    marginBottom: 15,
    // paddingHorizontal: 15,
  },
  similarProductCard: {
    width: '48%',
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 7, height: 7},
  },
  similarProductImage: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    marginBottom: 10,
  },
  similarProductName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  similarProductInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  similarProductRating: {
    fontSize: 12,
    marginLeft: 3,
    marginRight: 10,
    color: '#555',
  },
  similarProductDistance: {
    fontSize: 12,
    color: '#555',
    marginLeft: 3,
  },
  similarProductPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FE8C00',
  },
  noSimilar: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    marginTop: 10,
  },
  loadingContainer: {
    position: 'absolute',
    zIndex: 99,
    width: 60,
    height: 60,
    left: '44%',
    top: '42%',
    // elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 5, height: 5},
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
});
